{{ config(materialized='table') }}

--select EVENTS from VWE_DATABASE.PUBLIC.LATEST_CONVERSION where CONVERSION_STATUS = 'Converted' and EVENT_YEAR = 2021 group BY EVENTS
select INSERTION_ORDER, count(TOTAL_CONVERSIONS) as TOTAL_CONVERSIONS_COUNT from MULTI_ATTRIBUTION_DATASET where YEAR = 2021 group by INSERTION_ORDER
